# If running for the first time, the packages may need to be installed first using these lines:
#install.packages("countrycode","data.table","dplyr","eurostat","gdata","Hmisc","magrittr",
        #          "OECD","openxlsx","readxl","Rilostat","stringr","tidyr","xlsx","reshape2","xts", "diffr","tidyverse")

require( "countrycode" )
require( "data.table" )
require( "dplyr" )
require( "eurostat" )
require( "gdata")
require( "Hmisc" )
require( "magrittr" )
require( "OECD" )
require( "openxlsx" )
require( "readxl" )
require( "Rilostat" )
require( "stringr" )
require( "tidyr" )
#require( "xlsx" )
require("reshape2")
require("xts")
library("diffr") 
library("tidyverse")
library("extrafont")
font_install("fontcm")
